#!/usr/bin/env bash
# Parses Apache log files in list format.
#   it groups visitors by IP and HTTP status code.
#   and displays the number of occurrences, IP, and HTTP status

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
