#!/usr/bin/env bash
#shows "Best School" 10 times using a while loop.
#  with the 9th iteration, displays "Hi" before "Best School".

c=0


while [ $c -lt 10 ]
do
  if [ $c -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( c++ ))
done
